"""Pluggable embedding layer (design spec §7).

Embeddings are generated by Gemini (``GeminiEmbeddingProvider``); the ``EmbeddingProvider``
protocol is the seam ingestion and retrieval depend on. The active provider is built
per-request from the global Gemini key in ``api.deps.get_embedder``.
"""

from contextvault.embeddings.base import EmbeddingProvider
from contextvault.embeddings.gemini import GeminiEmbeddingProvider

__all__ = ["EmbeddingProvider", "GeminiEmbeddingProvider"]
