#!/usr/bin/env bash
#
# dev.sh — one command to bring up all of ContextVault for local development.
#
#   ./dev.sh
#
# It will, in order:
#   1. Ensure .env has an ENCRYPTION_KEY (generates one the first time).
#   2. Start Postgres + pgvector via docker compose and wait until it's ready.
#   3. Apply database migrations (alembic upgrade head).
#   4. Ensure an admin account exists with a KNOWN password (see below).
#   5. Launch the backend API (uvicorn, :8000) and the frontend (vite, :5173).
#
# Everything stops together when you press Ctrl+C.
#
# Login credentials (override by exporting before running, e.g.
#   ADMIN_USER=me ADMIN_PASS=secret ./dev.sh ):
ADMIN_USER="${ADMIN_USER:-admin}"
ADMIN_PASS="${ADMIN_PASS:-adminpass123}"

set -euo pipefail
cd "$(dirname "$0")"

BACKEND_PORT="${BACKEND_PORT:-8000}"
FRONTEND_PORT="${FRONTEND_PORT:-5173}"

log() { printf '\n\033[1;36m▶ %s\033[0m\n' "$1"; }

# --- 1. ENCRYPTION_KEY -------------------------------------------------------
log "Checking .env / ENCRYPTION_KEY"
[ -f .env ] || cp .env.example .env
if ! grep -q '^ENCRYPTION_KEY=' .env; then
  KEY="$(uv run python -c 'from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())')"
  printf '\n# Auto-generated by dev.sh — master key for encrypting provider API keys.\nENCRYPTION_KEY=%s\n' "$KEY" >> .env
  echo "  Generated a new ENCRYPTION_KEY and appended it to .env"
else
  echo "  ENCRYPTION_KEY already set"
fi

# --- 2. Database -------------------------------------------------------------
log "Starting Postgres (docker compose up -d)"
docker compose up -d

echo -n "  Waiting for the database to accept connections"
until docker compose exec -T db pg_isready -U contextvault -d contextvault >/dev/null 2>&1; do
  echo -n "."
  sleep 1
done
echo " ready."

# --- 3. Migrations -----------------------------------------------------------
log "Applying migrations (alembic upgrade head)"
uv run alembic upgrade head

# --- 4. Admin account --------------------------------------------------------
log "Ensuring admin account '$ADMIN_USER'"
ADMIN_USER="$ADMIN_USER" ADMIN_PASS="$ADMIN_PASS" uv run python - <<'PY'
import asyncio, os
from contextvault.db.session import SessionLocal
from contextvault.models import Role
from contextvault.services import users as user_service

username = os.environ["ADMIN_USER"]
password = os.environ["ADMIN_PASS"]

async def main() -> None:
    async with SessionLocal() as session, session.begin():
        user = await user_service.get_user_by_username(session, username)
        if user is None:
            await user_service.create_user(
                session, username=username, password=password, role=Role.ADMIN
            )
            print(f"  Created admin '{username}'.")
        else:
            # Reset to the known password so login always works in dev.
            await user_service.change_password(session, user, new_password=password)
            print(f"  Reset password for existing admin '{username}'.")

asyncio.run(main())
PY
echo "  → log in as: $ADMIN_USER / $ADMIN_PASS"

# --- 5. Frontend deps --------------------------------------------------------
if [ ! -d frontend/node_modules ]; then
  log "Installing frontend dependencies (npm install)"
  (cd frontend && npm install)
fi

# --- 6. Launch backend + frontend, tear down together ------------------------
PIDS=()
cleanup() {
  log "Shutting down"
  for pid in "${PIDS[@]}"; do kill "$pid" 2>/dev/null || true; done
  wait 2>/dev/null || true
  echo "  Backend + frontend stopped. (Database still running — 'docker compose down' to stop it.)"
}
trap cleanup INT TERM EXIT

log "Starting backend  → http://localhost:$BACKEND_PORT  (docs at /docs)"
uv run uvicorn contextvault.main:app --reload --port "$BACKEND_PORT" &
PIDS+=("$!")

log "Starting frontend → http://localhost:$FRONTEND_PORT"
(cd frontend && npm run dev -- --port "$FRONTEND_PORT") &
PIDS+=("$!")

echo
echo "───────────────────────────────────────────────────────────"
echo "  ContextVault is starting up."
echo "    App:      http://localhost:$FRONTEND_PORT"
echo "    API docs: http://localhost:$BACKEND_PORT/docs"
echo "    Login:    $ADMIN_USER / $ADMIN_PASS"
echo "  Press Ctrl+C to stop everything."
echo "───────────────────────────────────────────────────────────"

wait
