"""query_logs table

Revision ID: 550f1a28b886
Revises: ff19c3137fec
Create Date: 2026-07-18 08:37:21.967583
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '550f1a28b886'
down_revision: str | None = 'ff19c3137fec'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_logs',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('top_score', sa.Float(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('not_in_vault', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_query_logs_repository_id_repositories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_query_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_query_logs'))
    )
    op.create_index(op.f('ix_query_logs_repository_id'), 'query_logs', ['repository_id'], unique=False)
    op.create_index(op.f('ix_query_logs_user_id'), 'query_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_logs_user_id'), table_name='query_logs')
    op.drop_index(op.f('ix_query_logs_repository_id'), table_name='query_logs')
    op.drop_table('query_logs')
    # ### end Alembic commands ###
