"""Shared FastAPI dependencies for authentication and authorization."""

import uuid
from collections.abc import Awaitable, Callable

from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from sqlalchemy.ext.asyncio import AsyncSession

from contextvault.core.config import get_settings
from contextvault.core.tokens import InvalidToken, decode_access_token
from contextvault.db.session import SessionLocal, get_session
from contextvault.embeddings.base import EmbeddingProvider
from contextvault.embeddings.gemini import GeminiEmbeddingProvider
from contextvault.llm import LLMProvider, get_llm_provider
from contextvault.models import LLMProviderName, Repository, Role, User
from contextvault.services import providers as provider_service
from contextvault.services import users as user_service
from contextvault.services.ingestion import SessionFactory

_bearer = HTTPBearer(auto_error=False)

_UNAUTHENTICATED = HTTPException(
    status_code=status.HTTP_401_UNAUTHORIZED,
    detail="Not authenticated",
    headers={"WWW-Authenticate": "Bearer"},
)


async def get_authenticated_user(
    credentials: HTTPAuthorizationCredentials | None = Depends(_bearer),
    session: AsyncSession = Depends(get_session),
) -> User:
    """Resolve the bearer token to the current user, or raise 401.

    Authentication only — it does *not* enforce the forced-password-change bounce,
    so the change-password endpoint (the escape hatch) can depend on it while a
    user is flagged. Normal endpoints use :func:`get_current_user` instead.
    """
    if credentials is None:
        raise _UNAUTHENTICATED
    try:
        claims = decode_access_token(credentials.credentials)
        user_id = uuid.UUID(claims.subject)
    except (InvalidToken, ValueError) as exc:
        raise _UNAUTHENTICATED from exc

    user = await user_service.get_user_by_id(session, user_id)
    if user is None:
        raise _UNAUTHENTICATED
    return user


async def get_current_user(user: User = Depends(get_authenticated_user)) -> User:
    """The authenticated user, bounced if they owe a forced password change (card #27).

    A user with ``must_change_password`` set is stopped here — at the single auth
    chokepoint every protected endpoint funnels through — so recovery (design spec
    §2) forces the change before any normal request succeeds. The change-password
    endpoint depends on :func:`get_authenticated_user` instead, so it stays usable.
    """
    if user.must_change_password:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Password change required before continuing",
        )
    return user


def require_role(*allowed: Role) -> Callable[[User], Awaitable[User]]:
    """Build a dependency that passes only users whose role is in ``allowed``."""

    async def dependency(user: User = Depends(get_current_user)) -> User:
        if user.role not in allowed:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="Insufficient privileges",
            )
        return user

    return dependency


require_admin = require_role(Role.ADMIN)


async def get_embedder(session: AsyncSession = Depends(get_session)) -> EmbeddingProvider:
    """Build the Gemini embedder from the global provider key, or 409.

    Embeddings are global (one vector space for every repository), so the deployment
    must have a verified Gemini key — even for repositories that chat through another
    provider. Without it, ingestion and querying cannot embed, so fail fast with a
    clear, actionable message rather than deep in the pipeline.
    """
    settings = get_settings()
    key = await provider_service.get_provider_key(session, LLMProviderName.GEMINI)
    if key is None:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=(
                "Configure a verified Gemini API key to enable embeddings: embeddings "
                "for every repository are generated by Gemini."
            ),
        )
    return GeminiEmbeddingProvider(
        api_key=key, model_name=settings.embedding_model, dimension=settings.embedding_dim
    )


def get_ingestion_session_factory() -> SessionFactory:
    """Dependency yielding the session factory background ingestion opens.

    Defaults to ``SessionLocal`` so the background task gets its own session; tests
    override it to run ingestion inside their transaction.
    """
    return SessionLocal


RepoLLMBuilder = Callable[[AsyncSession, Repository], Awaitable[LLMProvider]]


async def build_repo_llm(session: AsyncSession, repo: Repository) -> LLMProvider:
    """Build the LLM provider a repository is configured to generate with (card #25).

    A repository picks a provider + model; the API *key* is shared from the global
    provider settings (``ProviderSetting``). Routing looks up that provider's key,
    decrypts it in memory, and constructs the matching provider so the query loop
    generates through the repo's chosen LLM. The query endpoint refuses repositories
    that aren't answerable (409) before reaching here, so provider, model, and a
    verified key are all present.
    """
    assert repo.llm_provider is not None
    api_key = await provider_service.get_provider_key(session, repo.llm_provider)
    assert api_key is not None, "provider key missing; caller must gate on answerability"
    return get_llm_provider(repo.llm_provider.value, api_key=api_key, model=repo.llm_model)


def get_llm_builder() -> RepoLLMBuilder:
    """Dependency yielding the per-repo provider builder (overridable in tests).

    The query endpoint (card #19/#25) resolves each request's provider from the
    target repository's chosen provider/model plus the global provider key through
    this seam; tests override it to route to a recording fake instead of constructing
    a real vendor client.
    """
    return build_repo_llm
